import { EventEmitter } from 'node:events'
import type { QuickTunnel } from '../shared/model'
import type { Supervisor } from './supervisor/process'
import type { CloudflareProvider } from './providers/cloudflare'
import type { LocalCacheStore } from './cache/store'

/**
 * Regex matching TryCloudflare random domain links generated by cloudflared.
 * Example log line:
 * |  https://random-words-1234.trycloudflare.com  |
 */
const TRYCLOUDFLARE_REGEX = /https:\/\/[a-zA-Z0-9-]+\.trycloudflare\.com/i

export function normalizeTargetUrl(input: string): string {
  const trimmed = input.trim()
  if (!trimmed) return 'http://localhost:3000'
  if (/^\d+$/.test(trimmed)) {
    return `http://localhost:${trimmed}`
  }
  if (!/^https?:\/\//i.test(trimmed)) {
    return `http://${trimmed}`
  }
  return trimmed
}

export interface QuickTunnelStartOptions {
  customId?: string
  mode?: 'trycloudflare' | 'custom_domain'
  customDomain?: {
    tunnelId: string
    hostname: string
    zoneId?: string
  }
}

export class QuickTunnelManager extends EventEmitter {
  private supervisor: Supervisor
  private getCloudflare?: () => CloudflareProvider | null
  private cache?: LocalCacheStore
  private tunnels = new Map<string, QuickTunnel>()

  constructor(
    supervisor: Supervisor,
    getCloudflare?: () => CloudflareProvider | null,
    cache?: LocalCacheStore,
  ) {
    super()
    this.supervisor = supervisor
    this.getCloudflare = getCloudflare
    this.cache = cache

    this.loadPersisted()

    // Intercept logs to extract the generated trycloudflare.com URL
    this.supervisor.on('log', ({ source, line }) => {
      if (!source.startsWith('quick:')) return
      const id = source.replace(/^quick:/, '')
      const tunnel = this.tunnels.get(id)
      if (!tunnel) return

      const match = line.match(TRYCLOUDFLARE_REGEX)
      if (match && (!tunnel.publicUrl || tunnel.status !== 'running')) {
        tunnel.publicUrl = match[0]
        tunnel.status = 'running'
        this.emit('update', tunnel)
        this.persist()
      }
    })

    // Intercept process state changes
    this.supervisor.on('state', ({ source, state, detail }) => {
      if (!source.startsWith('quick:')) return
      const id = source.replace(/^quick:/, '')
      const tunnel = this.tunnels.get(id)
      if (!tunnel) return

      if (state === 'crashed') {
        tunnel.status = 'crashed'
        tunnel.error = detail || 'cloudflared exited unexpectedly'
        this.emit('update', tunnel)
        this.persist()
      } else if (state === 'stopped') {
        tunnel.status = 'stopped'
        this.emit('update', tunnel)
        this.persist()
      } else if (state === 'running' && !tunnel.publicUrl) {
        // Still starting until publicUrl is discovered from log output
        tunnel.status = 'starting'
        this.emit('update', tunnel)
      }
    })
  }

  private loadPersisted(): void {
    if (!this.cache) return
    try {
      const raw = this.cache.getMeta('quick_tunnels')
      if (!raw) return
      const list = JSON.parse(raw) as QuickTunnel[]
      for (const t of list) {
        // If app restarted while TryCloudflare was running, process died with app
        if (t.tunnelType !== 'custom_domain' && (t.status === 'starting' || t.status === 'running')) {
          t.status = 'stopped'
        }
        this.tunnels.set(t.id, t)
      }
    } catch {
      // ignore
    }
  }

  private persist(): void {
    if (!this.cache) return
    try {
      this.cache.setMeta('quick_tunnels', JSON.stringify([...this.tunnels.values()]))
    } catch {
      // ignore
    }
  }

  async start(
    rawTargetUrl: string,
    options?: QuickTunnelStartOptions | string,
  ): Promise<QuickTunnel> {
    const opts: QuickTunnelStartOptions =
      typeof options === 'string' ? { customId: options } : options || {}

    const targetUrl = normalizeTargetUrl(rawTargetUrl)
    const isCustomDomain = opts.mode === 'custom_domain' && opts.customDomain

    if (isCustomDomain) {
      const { tunnelId, hostname, zoneId } = opts.customDomain!
      if (!tunnelId) throw new Error('Target tunnel ID is required for custom domain expose')
      if (!hostname) throw new Error('Hostname is required for custom domain expose')

      const cloudflare = this.getCloudflare?.()
      if (!cloudflare) {
        throw new Error('No Cloudflare account configured. Please connect your account first.')
      }

      const id = opts.customId || `qt_cd_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`
      const tunnel: QuickTunnel = {
        id,
        targetUrl,
        publicUrl: `https://${hostname.toLowerCase()}`,
        status: 'starting',
        createdAt: new Date().toISOString(),
        tunnelType: 'custom_domain',
        hostname: hostname.toLowerCase(),
        tunnelId,
        zoneId,
      }
      this.tunnels.set(id, tunnel)
      this.emit('update', tunnel)
      this.persist()

      try {
        await cloudflare.exposeHostname({
          tunnelId,
          hostname: hostname.toLowerCase(),
          service: targetUrl,
          zoneId,
        })
        tunnel.status = 'running'
        this.emit('update', tunnel)
        this.persist()
        return tunnel
      } catch (err) {
        tunnel.status = 'crashed'
        tunnel.error = err instanceof Error ? err.message : String(err)
        this.emit('update', tunnel)
        this.persist()
        throw err
      }
    }

    // TryCloudflare ephemeral mode
    const id = opts.customId || `qt_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`
    const procId = `quick:${id}`

    // Stop existing process if already running with this ID
    const existing = this.tunnels.get(id)
    if (existing && (existing.status === 'starting' || existing.status === 'running')) {
      return existing
    }

    const tunnel: QuickTunnel = {
      id,
      targetUrl,
      status: 'starting',
      createdAt: new Date().toISOString(),
      tunnelType: 'trycloudflare',
    }
    this.tunnels.set(id, tunnel)

    this.supervisor.spawn({
      id: procId,
      command: 'cloudflared',
      args: ['tunnel', '--url', targetUrl, '--no-autoupdate'],
      restart: false,
    })

    this.emit('update', tunnel)
    this.persist()
    return tunnel
  }

  async stop(id: string): Promise<boolean> {
    const tunnel = this.tunnels.get(id)
    if (!tunnel) return false

    if (tunnel.tunnelType === 'custom_domain' && tunnel.tunnelId && tunnel.hostname) {
      const cloudflare = this.getCloudflare?.()
      if (cloudflare) {
        try {
          await cloudflare.unexposeHostname({
            tunnelId: tunnel.tunnelId,
            hostname: tunnel.hostname,
            zoneId: tunnel.zoneId,
            deleteDns: true,
          })
        } catch {
          // best-effort unexpose
        }
      }
      tunnel.status = 'stopped'
      this.emit('update', tunnel)
      this.persist()
      return true
    }

    const procId = `quick:${id}`
    const stopped = await this.supervisor.stop(procId)
    tunnel.status = 'stopped'
    this.emit('update', tunnel)
    this.persist()
    return stopped
  }

  list(): QuickTunnel[] {
    return [...this.tunnels.values()]
  }

  get(id: string): QuickTunnel | undefined {
    return this.tunnels.get(id)
  }
}
