import { EventEmitter } from 'node:events'
import type { QuickTunnel } from '../shared/model'
import type { Supervisor } from './supervisor/process'

/**
 * Regex matching TryCloudflare random domain links generated by cloudflared.
 * Example log line:
 * |  https://random-words-1234.trycloudflare.com  |
 */
const TRYCLOUDFLARE_REGEX = /https:\/\/[a-zA-Z0-9-]+\.trycloudflare\.com/i

export function normalizeTargetUrl(input: string): string {
  const trimmed = input.trim()
  if (!trimmed) return 'http://localhost:3000'
  if (/^\d+$/.test(trimmed)) {
    return `http://localhost:${trimmed}`
  }
  if (!/^https?:\/\//i.test(trimmed)) {
    return `http://${trimmed}`
  }
  return trimmed
}

export class QuickTunnelManager extends EventEmitter {
  private supervisor: Supervisor
  private tunnels = new Map<string, QuickTunnel>()

  constructor(supervisor: Supervisor) {
    super()
    this.supervisor = supervisor

    // Intercept logs to extract the generated trycloudflare.com URL
    this.supervisor.on('log', ({ source, line }) => {
      if (!source.startsWith('quick:')) return
      const id = source.replace(/^quick:/, '')
      const tunnel = this.tunnels.get(id)
      if (!tunnel) return

      const match = line.match(TRYCLOUDFLARE_REGEX)
      if (match && (!tunnel.publicUrl || tunnel.status !== 'running')) {
        tunnel.publicUrl = match[0]
        tunnel.status = 'running'
        this.emit('update', tunnel)
      }
    })

    // Intercept process state changes
    this.supervisor.on('state', ({ source, state, detail }) => {
      if (!source.startsWith('quick:')) return
      const id = source.replace(/^quick:/, '')
      const tunnel = this.tunnels.get(id)
      if (!tunnel) return

      if (state === 'crashed') {
        tunnel.status = 'crashed'
        tunnel.error = detail || 'cloudflared exited unexpectedly'
        this.emit('update', tunnel)
      } else if (state === 'stopped') {
        tunnel.status = 'stopped'
        this.emit('update', tunnel)
      } else if (state === 'running' && !tunnel.publicUrl) {
        // Still starting until publicUrl is discovered from log output
        tunnel.status = 'starting'
        this.emit('update', tunnel)
      }
    })
  }

  start(rawTargetUrl: string, customId?: string): QuickTunnel {
    const targetUrl = normalizeTargetUrl(rawTargetUrl)
    const id = customId || `qt_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`
    const procId = `quick:${id}`

    // Stop existing process if already running with this ID
    const existing = this.tunnels.get(id)
    if (existing && (existing.status === 'starting' || existing.status === 'running')) {
      return existing
    }

    const tunnel: QuickTunnel = {
      id,
      targetUrl,
      status: 'starting',
      createdAt: new Date().toISOString(),
    }
    this.tunnels.set(id, tunnel)

    this.supervisor.spawn({
      id: procId,
      command: 'cloudflared',
      args: ['tunnel', '--url', targetUrl, '--no-autoupdate'],
      restart: false,
    })

    this.emit('update', tunnel)
    return tunnel
  }

  async stop(id: string): Promise<boolean> {
    const procId = `quick:${id}`
    const tunnel = this.tunnels.get(id)
    const stopped = await this.supervisor.stop(procId)
    if (tunnel) {
      tunnel.status = 'stopped'
      this.emit('update', tunnel)
    }
    return stopped
  }

  list(): QuickTunnel[] {
    return [...this.tunnels.values()]
  }

  get(id: string): QuickTunnel | undefined {
    return this.tunnels.get(id)
  }
}
